### ISSUE TITLE
Use of optional in new renderer is wrong

### ISSUE THREAD

**Issue by Vtec234** [SFTtech/openage#1058]
The new renderer demo is currently broken, because `<optional>` is somehow misused. Oddly enough, it works with `<experimental/optional>`, but after `optional` was included in standard C++ we switched to that. Some change of semantics must have occurred (probably UB in renderer) that breaks it.

**Comment by iicurtis** [comment]
Some more info:

One use of std::optional is broken, however using std::experimental::optional
works. Currently, this issue is with [simple_object.h](https://github.com/SFTtech/openage/blob/87c75b4b/libopenage/renderer/opengl/simple_object.h#L42).
```
std::optional<GLuint> handle;
```

Changing this to `std::experimental::optional` fixes the renderer demo. Interestingly, there does not seem to be any changes from experimental to iso std that might cause this, so my guess is the implementation changed.

Changing [buffer.cpp#L48](https://github.com/SFTtech/openage/blob/87c75b4b/libopenage/renderer/opengl/buffer.cpp#L48) to `glBindBuffer(target, this->handle.value());`
Breaks the code with 
```
Traceback (most recent call last):
  File "run.py", line 15, in init run
    main()
  File "/home/atraii/Downloads/Games/openage/openage/__main__.py", line 126, in main
    return args.entrypoint(args, cli.error)
  File "/home/atraii/Downloads/Games/openage/openage/testing/main.py", line 148, in main
    sys.exit(demofun(args.demo[1:]))
  File "openage/renderer/tests.pyx", line 50, in openage.renderer.tests.renderer_demo
    renderer_demo_c(renderer_test_id, root_cpp)
  File "../../libopenage/pyinterface/exctranslate.cpp", line 89, in void openage::pyinterface::translate_exc_cpp_to_py()
openage.cppinterface.exctranslate.CPPException: std::exception: std::bad_optional_access: bad optional access
```

This is likely the problem point.
