### ISSUE TITLE
Win10 - "CMake does not need to be run again"

### ISSUE THREAD

**Issue by m-luck** [SFTtech/openage#1096]
Really appreciate what's being done here. 

Are the Windows instructions up to date? I'm trying to install on my CUDA-enabled x64 WIN10 machine, however some of the instructions in the docs don't quite match. 

After following all that I can, there is no run.exe to be found. 

I ran everything, except for the FONTCONFIG_PATH, which I was not too sure what it was referring to. To install the font I simply clicked the fonts in the ttf folder instead of copying them over (I could not copy them over). Some of the folders are also slightly swapped. 

**In general, is there a quick update on the Windows side for instructions?** If I want to be able to run a project for my machine learning class using my favorite game, AOE, what do you all suggest for me? I have another (weaker) laptop running Arch, but I want to be able to utilize the power of my desktop GPU for a sort of realtime imitation learning project using the OpenAge API. VMware doesn't easily interface with GPUs. **Is my best bet just wiping my desktop OS and installing Linux?**

Very excited.

**Comment by heinezen** [comment]
Thanks :)

I think we moved only `run.py` to the `build` directory, not `run.exe`. You might want to check the `build` directory for `run.exe` and if that still doesn't work, you can come to the [Matrix chat](https://riot.im/app/#/room/#sfttech:matrix.org) for more extensive help.

> If I want to be able to run a project for my machine learning class using my favorite game, AOE, what do you all suggest for me? I have another (weaker) laptop running Arch, but I want to be able to utilize the power of my desktop GPU for a sort of realtime imitation learning project using the OpenAge API.

openage is unfortunately not in a state were we can use machine learning because the game simulation system of the engine is still missing. It's in the works right now (#1066), but will take more time to complete. Until then, I can only direct you to another machine learning project which tries to use the old 1999 version of the game. It's done by abductedPlatypus from the SiegeEngineers group ([Discord link](https://discord.gg/8JJQdk)). They are also not finished, but they should be closer to a working ML API than we are.

**Comment by m-luck** [comment]
Thank you, I haven't fixed this Windows issue but I got the Arch version up and running, because I just want to start playing around with things. And as you know, I have joined the two channels ;) Looking forward to this adventure.

**Comment by TheJJ** [comment]
Yay :)
