### ISSUE TITLE
Seeking to dispel doubts, running on vs2019

### ISSUE THREAD

**Issue by truewhite** [SFTtech/openage#1140]
I tried to compile and run this project in vs2019. When I run run.exe from the IDE, the error is as follows. What is the reason?
![image](https://user-images.githubusercontent.com/50393648/60446738-93100f80-9c54-11e9-8b16-08f38d78e736.png)
![image](https://user-images.githubusercontent.com/50393648/60446785-b0dd7480-9c54-11e9-8287-f4c7e7016414.png)

**Comment by TheJJ** [comment]
This error means that the `openage` python module was not found. It is exists in `builddir/openage`, so somehow the builddir is missing from your `PYTHONPATH`. Did you follow our windows building guide?

**Comment by simonsan** [comment]
I need it test out myself when I set up again the build/package VM soon. One step for diagnosing is using [ProcMon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to figure out which Libraries exactly are missing set the filter to `run.exe`. Otherwhise try to start openage with invoking `python run.py` and take a look for the error messages there. Sometimes the error messages are misleading, as it could be that a Qt-platform plugin is missing. @truewhite Did you compile or install pre-built Qt?

**Comment by Kafonin** [comment]
Ah, that reminds me.

I'd like to let you know @simonsan that _Qt failed to install_ when I tried to download all dependencies from the windows guide. That is pretty much the reason why I went straight to moving to ubuntu, because "Python" was missing when invoking the cmake command trying to build openage (just to try).

**Comment by simonsan** [comment]
@Kafonin What do you mean with `Qt failed to install`? The pre-built version or the vcpkg-version? Personally I did it several times while sticking completely to the windows build guide and it works. If Python is not found maybe you had another Python installation of a different version (2.x vs 3.x or 3_x86 vs. 3_x64) installed and both in the PATH environment variable? That could be a point why the right Python installation cannot be figured out automatically, then you need to invoke CMAKE with `-DPYTHON_EXECUTABLE` and other flags for libraries. We need to figure it out, how much of this troubleshooting things make sense to note somewhere, because systems differ much and a better way is definitely to ask in the various communication channels then of the team, I guess.

**Comment by Kafonin** [comment]
The vcpkg version. I had python 3.x and I just copied the dependencies I asked on riot but it wasn’t an important issue for everyone right now anyway, in my opinion, so I simply decided to try on Ubuntu. Good project, Linux is great.  :)

**Comment by TheJJ** [comment]
Okay :) If you encounter other problems, feel free to ask.
