### ISSUE TITLE
Inaccurate statement in doc/media/slp-files.md

### ISSUE THREAD

**Issue by metaptosis12** [SFTtech/openage#1144]
First I greatly appreciate the nice doc about SLP files [drs-files.md](https://github.com/SFTtech/openage/blob/master/doc/media/drs-files.md) in your repository, because that doc may be the most comprehensive one explaining SLPs that I can find on the whole Internet. :)

I'm recently trying to analyze one of my SLP files, and I'm using the doc as some basic resources. But I found some problems in that doc and it took me quite a long time to figure out the right way.
In drs-files.md you listed a couple of 'byte values' under the 'SLP drawing commands' section. After studying your [slp.pyx](https://github.com/SFTtech/openage/blob/master/openage/convert/slp.pyx) file I finally found out that the name 'byte values' is not accurate. For `0x00` and `0x01`, they mean 'the most insignificant (rightmost/lowest) two bits of `cmd_byte` being `0x00` and `0x01`, and `count` is equal to `cmd_byte >> 2`; For `0x02`, `0x03` and all the way to `0x0F`, they all mean 'the most insignificant (rightmost/lowest) 4 bits of `cmd_byte` being `0x02`, `0x03`, ..., `0x0F`.

I would suggest you to modify the text at the top of the chart 'byte value' to something like 'value of the most insignificant `n` bits' and note something like this in addition:

`if cmd_byte == 0x00 or cmd_byte == 0x01: n = 2; else: n = 4`.

Thx!

**Comment by heinezen** [comment]
I think the doc is basically trying to say what you wrote in the first sentence ("The image is drawn line by line, a line is finished with the "End of line" command (`0x0F`), where a command is a one-byte number (stored in the least-significant bits of the byte, e.g. `command = data & 0x0F`)") suggesting that you need to calculate the "command" first. `command` contains the 4 most significant bits from the data value and "byte value" refers to that. But you're right.. it is a bit convoluted and hard to understand for first readers :D I'm going to clarify the documentation in the next converter update and add some examples, so it's easier to understand.

> For `0x02`, `0x03` and all the way to `0x0F`, they all mean 'the most insignificant (rightmost/lowest) 4 bits of cmd_byte being `0x02`, `0x03`, ..., `0x0F`.

It's a bit more complicated because `0x04`, `0x08`, `0x0C` (all with lower crumb `b00`) are also "lesser block copy" and `0x05`, `0x09`, `0x0D` (all with lower crumb `b01`) are also "lesser block skip" commands. These commands are not used in AoE2, but in AoE1 and AoE1:DE. That's why slp.pyx checks for the `lower_bits` value instead of the lower nibble. Again, that's not super clear from the docs, so I'll change that soon.

**Comment by sandsmark** [comment]
I'm not sure if it's easier to read, but you can also look at the genieutils implementation; https://github.com/sandsmark/genieutils/blob/master/src/resource/SlpFrame.cpp#L437-L566

I've replaced the values with enum values in my genieutils fork, so you'll need to look here to see the values they map to; https://github.com/sandsmark/genieutils/blob/master/include/genie/resource/SlpFrame.h#L95-L121

I also find the aoetwols' implementations fairly easy to read (it has several, I think this is the most complete); https://github.com/aap/aoetwols/blob/master/shape.c#L205-L316

Lastly I have a very simplified implementation (without support for any of the "fancy" commands) of reading and writing SLP for the texture filtering for the terrains (the shading of the slopes): https://github.com/sandsmark/freeaoe/blob/master/src/resource/Terrain.cpp#L129-L198

But the openage doc is the best reference for almost all files in genie/aoe. I've been thinking about opening a PR importing most of the docs from aap, which complements the existing docs: https://github.com/aap/geniedoc

**Comment by heinezen** [comment]
@metaptosis12 #1148 contains an improved version of the documentation. Could you check if it's more understandable now? :)

@sandsmark You're welcome to make a PR and we would appreciate that :) I think most docs are in our repo already, but we might miss some.

**Comment by heinezen** [comment]
SLP documentation was revamped. If it there is still room for improvement for understanding the format, feel free to comment and reopen the issue.
