### ISSUE TITLE
Proposal: Version bump of dependencies

### ISSUE THREAD

**Issue by simonsan** [SFTtech/openage#1263]
The possible new version are the versions coming with **Ubuntu 20.04 LTS**. I marked the one's where I think we could bump the version and moved them to the very top.

Really happy I personally would be about another version bump of **CMake**, as that would enable us to work further on the Python3 stuff and actually use new methods for library linking (e.g. https://cmake.org/cmake/help/v3.13/command/add_link_options.html ) etc. The last bump I checked for Ubuntu 18.04 LTS dependencies.

If there are some advantages of bumping the **compiler versions** and **Cython** there @TheJJ has problably the most knowledge. 

For Qt I feel we should also bump, as I'm building currently on `5.14.2` in the CI, nevertheless, we should stick with the LTS version that is 5.12.x, which is also the last more open LTS I think ([5.15.x LTS will be only for commercial customers afaik](https://www.qt.io/blog/qt-offering-changes-2020)). For Qt we should also update QtQuickcontrols to Version 2 as Version one is throwing deprecated notes at us.

Probably also NumPy and Cython could get a version bump, I'm not very familiar with them both but I was seeing the deprecated warnings of an old NumPy-API lately - not sure, if that would change with the version bump though.

Dependency | Current Version | Possible New Version 
------------ | -------------| ---------------- 
**cmake** | >=3.12 | **3.16.3** :heavy_check_mark:
**Qt5** | >=5.9 | **5.12.8**
**QtQuickControls** | 1 | **2**
**python** | >=3.6 | **3.8.2**
**numpy** | / | **1.16.5**
**cython** | >=0.25 | **0.29.14**
gcc | >=7 | 9.3.0
clang | >=5 | 10.0
python imaging library (PIL) | / | 6.2.1
opengl | >=3.3 | (~3.14)
libepoxy | / | 1.5.4
libpng16 | / | 1.6.37
fonts-dejavu | 2.37 | 2.37
eigen | >=3 | 3.3.7
freetype2 | / | 2.10.1
fontconfig | / | 2.13.1
harfbuzz | >=1.0.0 | 2.6.4
ncurses | / | 6.2
jinja2 | / | 2.10.1
sdl2 | / | 2.0.10
sdl2_image | / | 2.0.5
opusfile | / | 0.9
opus | / | 1.3.1
ogg | / | 1.3.4
Vulkan | / | 1.2.131.2
([src](https://packages.ubuntu.com/search?suite=focal&section=all&arch=any&searchon=names))

What are your thoughts?

**Comment by simonsan** [comment]
`return ret` does not work on GCC 7.5.0 . Will try if it works for a later version.

_Originally posted by @duanqn in https://github.com/SFTtech/openage/pull/1260_

**Comment by TheJJ** [comment]
cxx features help for c++ aware people, but a user just needs to know the version they need installed, and they can look up in package archives if they have it.  For known distros we can of course say "you need ubuntu 20.04", but for all wild other distros its the easiest way to say the version number. One can figure out the version number by looking at the cxx status pages of clang and g++, but thats just a indirection we could provide ourselves. Internally, yes, we can use the feature checks, I'm not so sure how maintainable that is, to know when you used a feature for the first time and we need to add it to the buildsystem.

About the other version bumps:
Deprecated versions should be bumped, and our code ported. For each dependency we should have an issue where that bump is handled.

Non-deprecated versions can be updated, but only if we use a feature of them. Distros use the most recent versions anyway, what we require is minimum versions, and they should not be high just because we like big numbers. If a dependency's api is stable, we specify the minimum version that provides the features we need. If the api breaks with an update, we have to adapt and support the new interface (hopefully both, the new and the old api). If this is too much effort, we bump the minimum version and only support the newer version.

We can be pretty bleeding edge with this, but I think it's reasonable to only require libs that are available in latest stable ubuntu (not necessarily LTS), debian sid, archlinux, and gentoo. I'd even say we could list those as officially supported (although we'd of course fix any bug even on whatever toy distro). But those distros are what we try for minium available versions.

**Comment by simonsan** [comment]
@TheJJ Agreed, what would be the process if I would propose to pull another dependency, that is pretty much installed on most systems already and we deliberately check for it already, but don't state anywhere, that you could need it. I'm talking about **pkg-config**. I'm using it now in the updated `python.cmake` to get the right CFLAGS and LDFLAGS to compile the modules and executable. I would like to base on that in the future, because it can make platform independent (by letting pkg-config solve the dependency on the platform) builds much easier.

**Comment by TheJJ** [comment]
We should stick to CMake's version and flag detection mechanism: both pkg-config and cmake can be used to figure out include paths, flags, etc.

About the version bumps: I think they come naturally as soon as we need a feature of a dependencie's newer version.
Just bumping because we can doesn't help for portability or used features. Using the latest version is up to the distribution, anyway, we just define the needed minimum.

I don't think we rely on any deprecated API at the moment, and if we do, we should process them as separate issues -> closing.
