### ISSUE TITLE
Shipping to the "customers"

### ISSUE THREAD

**Issue by okias** [SFTtech/openage#1394]
Hey guys,

I know you perceive OpenAge like a code, where you can learn, design and play with new tech (well, it's not so new these days since time passed) but I was wondering, if it wouldn't make sense to release something, maybe not perfectly designed, but playable.

I already heard argument, that we can play AoE in wine, but I (and I believe so many people) would like to play some AoE in Linux with "pure Free software".

When I was writing Flatpak support for it, I was really hoping to play it at some point, but I'm little bit losing hope. Not asking for whole game, but at least some basic 1vs1 game, some stupid AI.. we have like Linux phones these days and it would be interesting to have at least few good games on them.

In case you don't planning to make at least some compromises, please at least provide ETA. If you cannot provide ETA, at least state, that waiting is futile (or you relying on someone stepping up and finishing it).

Thanks and good luck with coding.

**Comment by TheJJ** [comment]
hai! thank you for your patience :) don't loose hope, things will become better and better!
the problem is, creating a strategy game such as aoe is really not that easy, and we're all volunteers with other occupations (me for example currently doing my PhD). so people need a good motivation for this project. probably everyone sees that differently. if you just want to play aoe, you can use wine and be done.
so what's the point of openage? one of my motivations is to try to do things right, to build something cool, and not have some dumpster fire codebase with no flexibility and full of dirty hacks.
from that follows that the project needs a good foundation to run and develop the game, and that's what we've been doing since the start of the project, and plan on continuing, in the hope that it will pay off in two ways:
a) motivation: when you don't hate your codebase, you'll less likely give up, and
b) not building something obsolete because existing things are already better (which kinda leads back to a).

there have been many attempts on creating an open-source aoe, but so far not a single one remained alive until the delicate and nasty features were added properly, let alone a proper (modding) API. the "best" comparable project I know of is 0ad, developed since ~2001, and from their project you can estimate how much effort it is to create such a game.

for a volunteer project of high complexity, one of the things that help least is pressure, because giving in leads to the development process not being fun, or to messing up the codebase ("research grade code" due do deadline), so it's virtually impossible to name an ETA. I guess it's best to follow our status updates on reddit, and the pull requests.

so what can you do to accellerate our development? get involved! because that generates attention and leads to design decisions and code advancements, so we achieve the ultimate goal quicker: build an awesome game that is actually usable :)
