### ISSUE TITLE
How can I install openage with the AOE II HD from Steam?

### ISSUE THREAD

**Issue by cfunes401** [SFTtech/openage#1454]
Hello I don't known how to install openage with AOE of Steam: ( Sorry for my bad English)

**Comment by TheJJ** [comment]
Did you have a look at our installation documentation already?

**Comment by TobiasFP** [comment]
Dear Cfunes.
Installing Openage is currently something that only benefits developers, since the game is not playable at the moment.
If you want to contribute and have looked at the documentation, please inform us at least the following:
What have you tried already to get it up and running?
What OS are you on?(Linux, MacOS, indows)

**Comment by TheJJ** [comment]
I'll close this due to inactivity, but feel free to comment here again for further help (or ask in the chatroom).
