### ISSUE TITLE
Setup Installer

### ISSUE THREAD

**Issue by ShadowWarfare** [SFTtech/openage#1486]
Is it possible that a setup installer could be done for Openage like OpenMW which it retrieves the actual data files from the data disc and sets it up without the need to install wine?

**Comment by heinezen** [comment]
This would ideally be part of the game launcher (https://github.com/SFTtech/openage/issues/920). It calls the necessary CLI commands or provides an interface for them. You actually don't need Wine right now for conversion, since `python -m openage convert` should accept the raw files instead of a Wine installation.
