### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#285]
We really need some artwork.

* [x] Nice big logo/banner for the `README.md`, can be pixel or vector graphics (#319)
* [x] Square desktop icon, should be vector graphics (#319)
* [ ] Some fanart or whatever

**Comment by franciscod** [comment]
https://www.reddit.com/r/linux_gaming/comments/2xy9tf/openage_devs_no_binary_blobs_community_svg_gaben/

**Comment by JonasBorchelt** [comment]
😂👍

**Comment by TheJJ** [comment]
some [inspiration](http://trebuxet.deviantart.com/gallery/52719403/Age-of-Empires) from http://trebuxet.deviantart.com/:
![medieval battle](https://cloud.githubusercontent.com/assets/673543/7361432/7d9e0238-ed58-11e4-96f1-ee9da03cea6f.jpg)
![how do you turn this on](https://cloud.githubusercontent.com/assets/673543/7361433/82595854-ed58-11e4-83ac-8136159fa71d.jpg)

**Comment by franciscod** [comment]
Those are awesome! Let's ask him! :D

**Comment by detrumi** [comment]
As for the icon/logo: some of the AOE2 icons are a helmet. How about an open helmet for openage?

**Comment by franciscod** [comment]
the open helmet idea is awesome! ...what about gaben.svg with an open helmet?

**Comment by detrumi** [comment]
frickler01 has made [some sketches](https://github.com/frickler01/openage-design) for us! Let's give him some feedback. You can find a overview of his ideas [here](https://github.com/frickler01/openage-design/blob/master/sketches/sketches.md).

For the helmets, I liked # 6 the most recognizable AOE-like helmet.
Most of the escutcheon images are a bit too busy, I'd prefer something simple like # 14 (though # 18 is awesome too!)
The omega/A idea is awesome! Maybe use the omega as a helmet? # 20 looks nice, but having 'age' in it instead of just the 'A' would make it more recognizable.

**Comment by detrumi** [comment]
It would be nice to have a recognizable icon for openage. How do people feel about [this one](https://github.com/frickler01/openage-design/blob/master/svg/crown.svg)? It's already in `svg` format.

**Comment by linkmauve** [comment]
If you decide to go for this one, I wiped the unneeded attributes and the embedded PNG here, for a nice 46KiB → 955B ratio, and that’s before compression, where gzip can achieve a 491B file: http://linkmauve.fr/files/crown.svg

**Comment by franciscod** [comment]
gaben.svg clearly would apply as fanart...

**Comment by TheJJ** [comment]
We have a logo now (#319).
