### ISSUE TITLE
Why not FIFE?

### ISSUE THREAD

**Issue by frickler01** [SFTtech/openage#312]
I was reading around the nets and wondered why you don't use an existing 2D game engine like [FIFE](http://www.fifengine.net/). You could save a considerable amount of work for reinventing the wheel here and instead focus on actual game design.

Can anybody enlighten me about this decision?

**Comment by TheJJ** [comment]
The reason is pretty simple: When we started, we didn't want to finish the game as quickly as possible (because then wine is enough for the players i think), but rather implement it as awesome as possible.
Which is why we didn't even look at FIFE: to "invent things here" but of course can still be inspired by their ideas etc (0ad, openra, unknownhorizons are also very helpful).

Using an existing engine would limit us designing and extending any area of the code, no we can have a custom python interface, custom render code (e.g. for terrain blending), etc.

**Comment by frickler01** [comment]
I see. Though FIFE is supposed to be extensible, so terrain blending should not be an issue.

**Comment by mic-e** [comment]
I guess it is a strong case of NIH. I, and to some lesser extent, TheJJ, really like creating project infrastructure, and having control over the project.

We weren't aware of FIFE at the time (though I guess we could've checked that something like that exists).

Also, you might be underestimating the effort of fighting a possibly unstable, meagerly documented third-party API (it seems like their user's manual is still a TODO).

**Comment by frickler01** [comment]
@mic-e I definitely second the last one.

**Comment by TheJJ** [comment]
If we got more need for discussing this, it can be reopened of course.
