### ISSUE TITLE
openage Truck Factor

### ISSUE THREAD

**Issue by gavelino** [SFTtech/openage#339]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **openage** and obtained a value of **2**.

The developers responsible for this TF are:

Michael Ensslin - author of 58% of the files
Jonas Jelten - author of 45% of the files

To validate our results, we would like to ask **openage** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **openage**?

(b) Do you agree that **openage** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **openage** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by TheJJ** [comment]
Bwahaha :grin:

(a) Yes, this is true, but lately more developers started contributing.

(b) if i won the lottery, i'd develop openage full-time probably. But yeah, if both of us left, the project would be kind of unmaintained. I'm sure though somebody else would take over and a new community would form. Many people seem to be interested in this project, so the project death is probably not imminent then.

(c) We try do document code in two locations: In-source for stuff that accompanies code (Doxygen) and out-of-source for infos about file formats, concepts, implementation coherences, you get the idea (in the doc/ folder).
So the intention is that everybody should be able to understand each little corner of the project to be able to contribute and, in case of funny truck killings, be able to so without asking the original "inventors".

I do realize that most of the code is by @mic-e or me, but the project is designed to be open for everyone. More and more people are actively participating, so soon™ we'll take over the world because of our exceptional awesomeness and have millons of developers. Then we'll have enough power to control all the trucks in the world and prevent the truck factor being relevant by burning its roots.

**Comment by gavelino** [comment]
Thank you. I really appreciate the feedback.
