### ISSUE TITLE
Villagers continue collecting resources when told to move away.

### ISSUE THREAD

**Issue by darrenstrash** [SFTtech/openage#386]
The situation:

1. Villager is collecting resources
2. I right-click on terrain in a different location
3. Villager **correctly** moves to that location
4. Then, villager **incorrectly** goes right back to collecting the same resource.

**Comment by paddatrapper** [comment]
It looks like this is because the GatherAction's `on_complete` function is called once the action is finished and this does not distinguish between a direct command (right-click event) and depleting the resource. The `on_complete` function finds the closes resource of the type the villager was collecting and sets the villager to collect it.

I'll try fix this bug
