### ISSUE TITLE
Use opus/libogg API via cython instead of opusenc binary

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#434]
With our Cython interface, we can easily use the `opus` api directly to convert `wav` files to `opus`. For packing it in the `ogg` container, we must use `libogg`.
Should be a bit faster than the current approach of calling the `opusenc` binary for each conversion.

edit: changed from "use opusfile" to "use opus" because opusfile can't encode.

**Comment by castilma** [comment]
opusfile only supports decoding.

**Comment by TheJJ** [comment]
Right you are, thanks. https://github.com/xiph/opusfile I'll update the description.

**Comment by castilma** [comment]
I started working on this and I asked you, how to create a buffer(char *). You gave me these links.
[bytes - python doc](https://docs.python.org/3/c-api/bytes.html)
[example usage](https://github.com/SFTtech/openage/blob/master/openage/cabextract/lzxd.pyx#L104) [note line(s 6 and) 7]

But because byterrays are easier to handle, I tried to use them. 
[bytearray - python doc](https://docs.python.org/3/c-api/bytearray.html)

note, that i searched for header files that contain the functions mentioned in the bytearray doc but didn't find any. 
maybe, you don't really need those functions:
[encoding 'text' to bytes](http://docs.cython.org/en/latest/src/tutorial/strings.html#encoding-text-to-bytes)

[please look at 'write_opus_header'](https://github.com/castilma/openage/tree/pyopus)
this doesn't compile yet. partly, because dereferencing `op` throws an error.
`*op.packet =...`
but op is a pointer, '->' doesn't work either. how is that supposed to be?

and did I make an error by using bytearray because of it's easier usage?

2 problems so far, and I still need to get my head around cython.

**Comment by TheJJ** [comment]
Basically we have to create a simplified version of [the opusenc tool](https://git.xiph.org/?p=opus-tools.git;a=blob;f=src/opusenc.c).
For the header creation, they use `opus_header_to_packet`.

You should handle all the data in the conversion as bytes directly. In `opusenc`, they also know the block size beforehand, which is why I suggested that you use `bytes` instead of a `bytearray`. But it should not matter. Nevertheless, I think it will be easier to stick to `bytes`.

`bytes` can directly be casted to `unsigned char *` (see the `lzxd.pyx`) (not sure about `bytearray`).

If you create regular python objects, then they are garbagecollected because of their reference counting.

For dereferencing memory, you can use the `dereference` function:
`from cython.operator cimport dereference as deref`, then `deref(something)` is the same as `*something`. I couldn't find the source code for that in cython, wtf..

**Comment by castilma** [comment]
I got the most things working. The main thing missing right now is resampling. If anyone wants to contribute, see [here](https://github.com/castilma/openage/tree/pyopus).

**Comment by TheJJ** [comment]
Well done! You can create a `[WIP]` pullrequest if you like, then we can do easier reviews there.

**Comment by TheJJ** [comment]
wheeeeeee
