### ISSUE TITLE
Consistently use openage::util::hash_combine()

### ISSUE THREAD

**Issue by lyle-nel** [SFTtech/openage#468]
I have tracked down 3 places that use a different hash implementation than that defined in `libopenage/util/hash.h`. However, both implementations seem to serve the same purpose, that is, combine two hashes.

For the sake of consistency it might be good to reuse that function instead of having two implementations.

The places in question are:

https://github.com/SFTtech/openage/blob/master/libopenage/coord/phys3.h#L72-L74
https://github.com/SFTtech/openage/blob/master/libopenage/coord/tile.h#L75-L79
https://github.com/SFTtech/openage/blob/master/libopenage/pathfinding/path.h#L207-L209

**Comment by okovko** [comment]
Boost does not advise using its hash function as a general purpose hash function

http://www.boost.org/doc/libs/1_49_0/doc/html/hash/rationale.html

**Comment by TheJJ** [comment]
`if you do need a higher quality hash function, then neither the standard hash function or boost::hash are appropriate`, but we just wanna have a high probablility of non-colliding hashes for any sort of container.

For any crypto needs, we will go with `libsodium` and of couse not with those non-cryptographic hashes.

**Comment by okovko** [comment]
As far as integrals are hashed, the output of hash is simply the input you gave it anyways.

The Boost hash_combine() should serve that purpose (high probability of non-colliding hashes) for integral pairs. 0x9E3779B9 is 2 ^ 32 / phi; a 32 bit binary expansion of an irrational number provides 32 uniform bits with no simple correlation. The xor will generate distinct hashes for similar inputs because it smudges the leading and trailing bits of hash2 + inv_phi_32 by adding the shifts of hash1 + inv_phi_32.

Note that Boost's hash_combine() expands to

hash1 + inv_phi_32    ^    hash2 + inv_phi_32 + ( ( hash1 + inv_phi_32 ) << 6 ) + ( ( hash1 + inv_phi_32 ) >> 2 )

Whereas the openage::util::hash_combine() expands to

hash1    ^    hash2 + inv_phi_32 + ( hash1 << 6 ) + ( hash1 >> 2 )

Here, hash1 has little effect on the output of the xor, and there's generally less bit shuffling. I would think there will be more collisions relative to the Boost hash_combine(), and the distribution of pairs -> hashes will be whacky? I could be missing a specific reason it's written this way.

The custom hash in the links simply left rotates hash1 by 1 bit before xoring it with hash2. This hash shuffles the bits a lot less and doesn't have a uniform basis, so I think collisions would  be skewed and more common in general. It seems safe to replace the custom hash with Boost's hash_combine(), but perhaps there is a specific reason the author chose to hash the values this way.

Can I get assigned to this?

**Comment by franciscod** [comment]
My vote is to use hash_combine everywhere except for crypto, and dont overthink this very much, it's already solved elsewhere

**Comment by TheJJ** [comment]
@okovko sure, just go a head and submit pullrequests as you like, we don't use "official" assignments. But keep in mind that i will defend openage from using boost to my death.

Feel free to improve our hash combination function though, maybe you can even make it portable for 32bit and 128bit or something :)

**Comment by okovko** [comment]
:p

I should have mentioned that the openage hash_combine() is SUPPOSED to behave the same way as boost's hash_combine(), as the comment says the code is from boost. It's just a ripped one-liner. There was a little adjusting though, and that made it wrong :(

**Comment by okovko** [comment]
@TheJJ will do :)

**Comment by TheJJ** [comment]
@okovko did you try it already? would be cool :stuck_out_tongue:

**Comment by TheJJ** [comment]
@okovko any progress so far? else, maybe somebody else may resolve it.

**Comment by TheJJ** [comment]
done in #1110
