### ISSUE TITLE
libopenage/unit/type_pair.h - what is it?

### ISSUE THREAD

**Issue by ChipmunkV** [SFTtech/openage#489]
It confuses the code navigation a bit.

**Comment by TheJJ** [comment]
Basically this is the to-be-done interface for nyan.

Nyan will provide unit types by overlaying all kinds of attributes at loadtime and runtime.
That way, mods and research discoveries are the same.

We still made no progress developing nyan #239, but that's ok as I think other parts of the game still have priority because the game foundation isn't layed out properly so that a "real" unit system makes sense.

**Comment by TheJJ** [comment]
Leave a comment if you got further questions to this :)
