### ISSUE TITLE
Build status/link

### ISSUE THREAD

**Issue by janisozaur** [SFTtech/openage#587]
https://github.com/SFTtech/openage/blob/8f3fbf81c11e3503ff688fbd4d30df3917e89721/doc/code/testing.md

Mentions:

> All tests are run automatically by Travis, via `python3 -m openage.testing -a`.

But travis was replaced with kevin.

Independent of this issue: There's also no link/badge pointing to most recent kevin build in readme.md.

**Comment by zuntrax** [comment]
Kevin runs the sanity check with `make checkall`.

AFAIK, kevin does not yet support badges, but generating one probably boils down to a bunch of imagemagick calls. However, a badge is kind of pointless without a decent web interface. Last time I started looking into it, a ragequit occured because npm (needed for Ember.js) was cumbersome on my distro of choice. Maybe it's time to try that again.

**Comment by janisozaur** [comment]
Have you seen http://shields.io/ ?

**Comment by TheJJ** [comment]
Heh :)
The "true" approach is a badge action in kevin, which generates a symlink to the correct badge in the build folder. But so far I didn't have time/motivation for implementing that in kevin.

**Comment by TheJJ** [comment]
This was fixed in 039b1962eb695de4395584f1e73bf270c0d4ee51. The kevin badge is still missing, but that is something for SFTtech/kevin#11.
