### ISSUE TITLE
Units can be selected through the UI

### ISSUE THREAD

**Issue by elnabo** [SFTtech/openage#611]
Units hidden behind the bottom UI can be selected and their health bars will appear.

![https://i.imgur.com/dDjVoF2.jpg](https://cloud.githubusercontent.com/assets/673543/18847583/17eed9a6-842b-11e6-9329-85b253529200.jpg)
##

**Comment by ChipmunkV** [comment]
It's intended that they can be selected with a rectangular frame selection through the UI (if that selection doesn't start on the UI).

But the health bars of the selected units must not be above the UI. There are two possibilities: move drawing of the the healthbars overlay to be before the GUI overlay or draw them as a minimap from #559 (bonus: they are customisable with QML, so there are colours/segments/numbers/animations through scripting+hotreload).

**Comment by elnabo** [comment]
Why is it intended ? I believe it doesn't work in the base game.

**Comment by ChipmunkV** [comment]
GUI elements shouldn't block the rectangle from expanding, because it breaks the fluidity. So, just filtering the events won't work. The way to do it is to test each unit-about-to-be-selected against the geometry of the GUI.

There were transparent GUI elements in some test/editor modes that annoyed me when they blocked the selection.

Current implementation is not limiting the player and there is no subsystem that deals with the GUI's geometry to maintain.
