### ISSUE TITLE
NixOS packaging and new release

### ISSUE THREAD

**Issue by pstn** [SFTtech/openage#667]
Hi, I'm currently packaging this game for nixos, mainly to play around with it and to have a little fun.
I just noticed that your latest release still depends on ftgl, that you removed more than a year ago.
Could you maybe do a new release with the new dependencies?

**Comment by TheJJ** [comment]
Yes, we should really do it.. The main "blocker" is that the `make install` still isn't fixed currently, and out-of-source-builds are kinda broken. I think qml files aren't found when they are installed in `/usr/share/openage` or something.

But, as nixos is totally not `lsb`, would be awesome if you could hint us what needs to be more dynamic and improved to make our packaging capabilities as good as possible.

We didn't care much about packaging so far because openage is not ready for endusers. The devs just clone the repo and we tried to optimize the developer experience only. But, of course, we care for packagers as well but they have to tell us what is broken :)

**Comment by pstn** [comment]
I'm having some trouble setting the python prefix, I was under the impression that this should be done via 

    ./configure --py-prefix=$prefix #$prefix is defined by my package manager

but it doesn't seem to have any effect on my build.

Btw. One thing I'd like the ./configure script to do is to have a mode where it prints the exact arguments it got. Many distributions assume autotools and not "autotool like behaviour" when they find a configure script and there things might break. (Just to be clear: This is no criticism of your choice of build tools, I'm personally also not a big fan of autotools, but that's what we are stuck with for now)

**Comment by TheJJ** [comment]
You are aware that this is a "regular" cmake project, right? You will have a way easier job using cmake directly when packaging i guess :grinning: 

What do you mean with "print exact arguments" `./configure` got?

If it leads to confusion, we should maybe prevent `./configure` being mixed up with autocancer somehow.

**Comment by TheJJ** [comment]
Can you elaborate on that so we can enhance the packaging experience?

**Comment by zuntrax** [comment]
@pstn I ran into the same issue last time I played around with a nixos build. When you add `cmake` to the build environment, hooks are injected into most of the phases, replacing all the autotools-style calls with `cmake`. See [this one](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/cmake/setup-hook.sh) for the magic that happens. You probably want to add `-DCMAKE_PY_INSTALL_PREFIX=/nix/store/whatever` to your cmake invocation. `configure` is just a wrapper around `cmake`, I'll attach the part of the output generated before running `cmake`. If I got the point, this should be exactly what you wanted to have :smile: 
<details>
<summary><tt>configure</tt> before running <tt>cmake</tt></summary>
<pre>
./configure is a convenience script:
it creates the build directory,  symlinks it,
and invokes cmake for an out-of-source build.<br />
Nobody is stopping you from skipping ./configure and our Makefile,
and using CMake directly (e.g. when packaging, or using an IDE).
For your convenience, ./configure even prints the direct CMake invocation!<br />
         build_type | Debug
       cxx_compiler | g++
          cxx_flags | 
   exe_linker_flags | 
     install_prefix | /usr/local
module_linker_flags | 
  py_install_prefix | /foo
shared_linker_flags | <br />
config options:
          backtrace | if_available
gperftools-profiler | if_available
gperftools-tcmalloc | False
            inotify | if_available<br />
bindir:
/home/zuntrax/git/openage/.bin/g++-debug-Oauto-sanitize-none/<br />
invocation:
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='' -DCMAKE_EXE_LINKER_FLAGS=''
-DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_MODULE_LINKER_FLAGS=''
-DCMAKE_PY_INSTALL_PREFIX=/foo -DCMAKE_SHARED_LINKER_FLAGS=''
-DCXX_OPTIMIZATION_LEVEL=auto -DCXX_SANITIZE_FATAL=False
-DCXX_SANITIZE_MODE=none -DWANT_BACKTRACE=if_available
-DWANT_GPERFTOOLS_PROFILER=if_available -DWANT_GPERFTOOLS_TCMALLOC=False
-DWANT_INOTIFY=if_available -- /home/zuntrax/git/openage
</pre>

Feel free to poke me in IRC. I forgot a lot since then, but maybe I can still help a bit.

**Comment by zuntrax** [comment]
@pstn We will fix the buildsystem issues and then bump the version to `0.4.0`.

**Comment by TheJJ** [comment]
@pstn please test my branch #723 and see if it is friendlier for packaging

**Comment by pstn** [comment]
Without any further configuration the builder still wants to install into the python package dir:
  
    ...
    [ 99%] cropping gaben.png to create placeholder desktop icon
    glibPreInstallPhase
    installing
    install flags: install SHELL=/nix/store/010yd8jls8w4vcnql4zhjbnyp2yay5pl-bash-4.4-p5/bin/bash   gsettingsschemadir=/nix/store/pixax0ph2
    h5y5s8m1ind3yms97v2bv8q-openage-0-4-0/share/gsettings-schemas/openage-0-4-0/glib-2.0/schemas/
    [  0%] Automatic moc for target libopenage
    Install the project...
    -- Install configuration: "Release"
    CMake Error at cmake_install.cmake:44 (file):
      file cannot create directory:
      /nix/store/wkl9lz79bdq503b3a22hpjblxj61r081-python3-3.5.3/lib/python3.5/site-packages/openage.
      Maybe need administrative privileges.

**Comment by TheJJ** [comment]
Where should it install instead automatically?  And with "further configuration", you mean `--py-prefix` or the `-DCMAKE_PY_INSTALL_PREFIX` option?

How should it behave instead?

**Comment by pstn** [comment]
Ah, now I see what you are doing. I guess it's reasonable to do that. I'll go and fix my package tonight and come back to you.

**Comment by TheJJ** [comment]
Be sure to use the latest master from like 10 minute ago as many installation improvement changes just got merged (#723).

**Comment by pstn** [comment]
Thanks. I've come much further now and it's been a much nicer process.
Would it be possible for you to give a compile time option where to install the configs to?
It's currently hard coded to ``/etc`` but for example on nix that doesn't work because user without administrative privileges can install software. Or maybe just give an option to disable it completely since it doesn't seem critical to me.

**Comment by TheJJ** [comment]
Okay, so you wanna customize the `INSTALLED_GLOBAL_CONFIG_DIR`? Did you use cmake directly or the `./configure` helper script?

**Comment by pstn** [comment]
Yes, I do.
I (or rather nix) is using cmake directly.

**Comment by TheJJ** [comment]
I added it, you could be able to customize with `-DGLOBAL_CONFIG_DIR` and (optionally) `-DGLOBAL_ASSET_DIR`.

**Comment by TheJJ** [comment]
I assume that the configuration should now be possible for you. If not, please shout :)
