### ISSUE TITLE
Create a better sprite format

### ISSUE THREAD

**Issue by Jon0** [SFTtech/openage#697]
Converting from slp to png seems to lose some of  the original information, which pixels are part of the outline, or which are real colours, or player colours.

For use in opengl or vulkan, we could save multiple layers per converted slp file:
1: Sprite plain colours as RGB
2: Player colours: mono (later replaced in shader, with player colour)
3: Outlines: mono (later replaced in shader, with player colour)

Maybe use a different format (can png save multiple layers in one file?)
or create a new format, probably just some container for png, and save to different files in conversion.

**Comment by TheJJ** [comment]
The information is not lost, instead, we encode it [in the alpha channel](https://github.com/SFTtech/openage/blob/30980f60edee1d8185b5494625430f1bac4ecd32/openage/convert/slp.pyx#L546).

We should try to keep common formats so that people can easily edit the files for modding.
An option could be having multiple files with suffixes like `.._playercolors.png` and `.._outlines.png`.
But this multiplies the amount of files by factor 3. This may also complicate things when editing.

A solution would be a "common" image format that supported 5 channels: `(r, g, b, a, special)`.

**Comment by Jon0** [comment]
Ok I missed how the alpha worked. if the extra channels are all exclusive that works.
Maybe use ``alpha = c + base_pcolor`` with some constant c, for player colours, in case modified / custom png assets collide with the default player colours. Also how many colours should be given to each player?

They can be separated into layers when loading too. I'm not sure how to make shaders with outlines appearing in front. maybe the depth buffer could be used in reverse somehow.

 Is the rendering branch still being used for this stuff?

**Comment by TheJJ** [comment]
First, draw the scene like normal. Then, as next pass for the outline rendering we can basically use a shader to draw just outline pixels with a fixed color if things are obstructed (aka inverted depth buffer).

Yes, my `rendering` branch is up to date and compiles. @Vtech234 has started to think about the new renderer architecture.

**Comment by TheJJ** [comment]
Do you have a better idea how we can store the additional information without having multiple files per sprite?

**Comment by detrumi** [comment]
We'll most probably need multiple files anyways, as we already have shadow textures in different files. I don't think keeping every part of a sprite really helps, especially if you have shadows, animations, or multiple sprites in a single file. Maybe we should use a standard naming scheme for different parts of the texture, and use a single folder for each sprite.

**Comment by TheJJ** [comment]
This is very related to #965
