### ISSUE TITLE
Limit Python line length to 79 chars

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#716]
Currently, we allow a line length of `100` in `etc/pylintrc`.
To adhere common python code style, we [should lower that to `79`](https://www.python.org/dev/peps/pep-0008/#maximum-line-length).

This means a lot of code fixing though, so it can be done over time.

To find problematic lines, change the line length in your `pylintrc` and run
``` bash
p3 -m buildsystem.codecompliance --pylint
```

Then a lot of errors should show up where you'd have to beautify the code and reduce the line length.

EDIT: **we decided to vote on the allowed line length**:
React with thumbs up for 79, thumbs down for 100, confused for 119, laugh for 99.

**Comment by zuntrax** [comment]
I'd stay with 100. I'd say up to 120 is still reasonably readable. Changing all that code is a lot of effort, but I don't think it will make that big of a difference.

**Comment by mic-e** [comment]
I'm undecided. In the past I've had many cases where I introduced ugly line breaks to comply with PEP8, effectively lowering the overall readability of the file, IMO. pylint's docs themselves show some understanding for the wish to allow longer lines.

**Comment by TheJJ** [comment]
So you think it's better we left it as-is?

**Comment by mic-e** [comment]
As I said, I'm undecided. Democracy?

**Comment by TheJJ** [comment]
Then i'd say we'll wait a few weeks and let people vote on the top post. I'll start.

**Comment by mic-e** [comment]
IMO our options are 79 chars, 99 chars, 100 chars and 119 chars. React with thumbs up for 79, thumbs down for 100, confused for 119, laugh for 99.

Democracy: It works the better the more complicated elections become!

**Comment by zuntrax** [comment]
Wow.

**Comment by iNaKoll** [comment]
Maximum line length is all about readability. Really ? I'd say that a line length of 100 is a good compromise between the reader and the writer. Sometimes when I use my 11" laptop I can really see the point of having a 80 column code. If someone really enjoy the 80 column and is ready to make this change I think no one (not even democracy) should prevent that person from doing it.

PEP8 says 

> The default wrapping in most tools disrupts the visual structure of the code, making it more difficult to understand. The limits are chosen to avoid wrapping in editors with the window width set to 80, even if the tool places a marker glyph in the final column when wrapping lines. Some web based tools may not offer dynamic line wrapping at all.

My editor is configured to place marker glyph in the final column and I don't really see the point for 79 instead of 80... whatever...

> Some teams strongly prefer a longer line length. For code maintained exclusively or primarily by a team that can reach agreement on this issue, it is okay to increase the nominal line length from 80 to 100 characters (effectively increasing the maximum length to 99 characters), provided that comments and docstrings are still wrapped at 72 characters.

IMO 100 or 99 would be OK for openage.

> The Python standard library is conservative and requires limiting lines to 79 characters (and docstrings/comments to 72).

PEP8 choice (79 line length) is universally "conservative" from the point of view of a reader with a really low screen resolution. We are in 2017 and everyone will soon have one or two 8K monitors so the question is who really cares?

**Comment by TheJJ** [comment]
So, after some time, the voting is over with:
* 1 for 79
* 3 for 100
* 2 for 99
* 2 for 119

➡️  we'll keep it as-is, 100..
