### ISSUE TITLE
Alias Thread IDs to smaller numbers

### ISSUE THREAD

**Issue by MaanooAk** [SFTtech/openage#902]
Anyone else gets this:

![screenshot from 2017-08-30 00-41-55](https://user-images.githubusercontent.com/6997990/29845641-5a1c2d9c-8d1c-11e7-99ca-6c1828fd75d6.png)

Shouldn't that be T1?

**Comment by TheJJ** [comment]
It should be, yes. I've seen it a few times for others now, but for me it looks like it should.

It looks like the variable may be uninitialized and has garbage values then.

![2017-08-30t00 16 27 286483433 02 00](https://user-images.githubusercontent.com/673543/29846858-f2651dc4-8d18-11e7-8d7f-2e671c2c1b87.png)

(Are you in our IRC/Matrix channel? Because it would be nice if we could communicate more in real-time for the architecture work and general game simulation integration with curves, eventtriggers, nyan, the renderer etcetc. You would likely be a valuable contributor for this.)

**Comment by castilma** [comment]
what are you configure flags for that build?

**Comment by MaanooAk** [comment]
I now get `T1` again and I can't reproduce the bug :(

**Comment by castilma** [comment]
for me, building current (3b1d68ef25911e9f5baab6083d6e46f278231e75) with addressanitizer triggers this.

**Comment by TheJJ** [comment]
I think the numbers are not wrong: They're hashed if `openage` is built without thread local storage:

https://github.com/SFTtech/openage/blob/20cdb818ab8f859401f3a056c280a3b55048be6d/libopenage/util/thread_id.cpp#L44-L51

In http://en.cppreference.com/w/cpp/thread/get_id we can see that we have to hash the `id` in order to have it as numerical value. This means we likely have to maintain a map of those thread ids to the monotonically increasing value to get rid of the high numbers and start with 0 instead.

**Comment by castilma** [comment]
why do we hash the id? and why doesn't get_id() start with zero but returns arbitrary numbers?

**Comment by TheJJ** [comment]
It returns a [`std::thread::id`](http://en.cppreference.com/w/cpp/thread/thread/id), which is not a number, but some struct.

**Comment by TheJJ** [comment]
So, the only way to get rid of those high numbers is to maintain a `unordered_map` of `std::thread::id => size_t`: the key are the registered thread ids, the value is a monotonically increasing index.

For display, the thread id is looked up and we display the value.

**Comment by heinezen** [comment]
afaik this is implemented by now
