### ISSUE TITLE
Suggestion: Tag system

### ISSUE THREAD

**Issue by MaanooAk** [SFTtech/openage#906]
### Current system: Classes

- HumanWithBow: **archer**
- HumanOnHorse: **cavarly**
- HumanOnCamel: **cavarly**
- HumanOnHorceWithBow: **cavarly_archer**

### Suggested system: Classes with Multiple Inheritance

- HumanWithBow: [**Archer**]
- HumanOnHorse: [**Cavarly**]
- HumanOnCamel: [**Cavarly**]
- HumanOnHorceWithBow: [**Cavarly**, **Archer**]

### Suggested system: Tags

- HumanWithBow: [**human**, **range**, **archer**, **with_bow**]
- HumanOnHorse: [**human**, **melee**, **cavarly**, **on_horse**]
- HumanOnCamel: [**human**, **melee**, **cavarly**, **on_camel**]
- HumanOnHorceWithBow: [**human**, **range**, **cavarly**, **archer**, **on_horse**]

Thoughts?

**Comment by TheJJ** [comment]
+1 would be much better for modding, and even though I never called it out that way this is what I imagined how unit types are created.

We can do that either with inheritance in nyan or with set members. Can't really say what is better, altough I think inheritance will suit better.

**Comment by MaanooAk** [comment]
So you are talking about multiple inheritance, in order to achieve multiple classes instead of one. (I forgot about the multiple inheritance)

Another concern is how a patch could add a new class, but it can be done based on the specification :)

I cant find any other case that inheritance can't do something that tags can. 
So at the moment the **Multiple Inheritance** is the way to go.

**Comment by Tomatower** [comment]
I think the tags should be more atomar:

* *AttackTypes*: What kind of Attack can this Unit perform `RangedAttack, CloseAttack, ContinuousAttack, PoisonAttack,`
* *Weaknesses* What are the Weaknesses? `WeaknessRanged, WeaknessPike`, ...
* *Targetability*: Is this targetable by the player? `TargetPlayer, TargetWorld`
* *Ressources*: Is this a ressource? `IronRessource, GoldRessource, ...`
* *Core Engine Abilities*: Core features the above can be reduced to `Damage, MovementCommand, Patrol, Follow, Construct, ...`

What additional types do we need?

**Comment by heinezen** [comment]
I think tags have another great advantage because they can be assigned during an ongoing game. There would be two types of tags:

* **Pre-assigned tags:** Basically what @MaanooAk and @Tomatower already described. These would all be inherited from the respective classes and are already assigned when an object is created. Examples: [human, melee, ranged]
* **Runtime-tags:** These are tags that can be added to individual units at run-time, for example when they perform an action or when they become a mission goal during a scenario. Would also make sense to tag converted units with this mechanism. Examples: [converted, buffed, immortal]

**Comment by TheJJ** [comment]
I'd say we move the discussion to the #816 otherwise we'll scatter the info too much :)
