### ISSUE TITLE
Replacing relative imports with absolute imports

### ISSUE THREAD

**Issue by PythonicChemist** [SFTtech/openage#927]
All package specific imports are imported via importing relative for example:

``` python
import .math
```

instead of:

``` python
import openage.util.math
```

Relative imports have various disadvantages like not working when directly invoking the file or being less readable in my opinion. I'd like to go through all the project's imports and switch them over to absolute imports.

What are you thoughts? This change would bite with `/openage/util/math.py` and have to be renamed to circumvent it importing itself.

**Comment by TheJJ** [comment]
@mic-e said there was some technical reason for the cython interface. I wouldn't convert it because it allows that scripts can be run not only from the project root.

But I think this is a matter of presonal preference. Hard to tell what is better. I like them because of less redundancy.

https://docs.python.org/3/tutorial/modules.html#intra-package-references
